name: Rust nightly Build

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create or update nightly tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f nightly
          git push origin nightly --force

      - name: Create or update nightly release
        uses: taiki-e/create-gh-release-action@v1
        with:
          ref: refs/tags/nightly
          title: Nightly Build
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & upload binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          ref: refs/tags/nightly
          bin: slipstream-client slipstream-server
          target: x86_64-unknown-linux-gnu
          tar: all
          token: ${{ secrets.GITHUB_TOKEN }}
