name: Rust nightly Build

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set nightly tag
        id: nightly_tag
        run: |
          TAG="v0.0.0-nightly-$(date +'%Y%m%d%H%M')"
          echo "NIGHTLY_TAG=$TAG" >> $GITHUB_ENV
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f $TAG
          git push origin $TAG --force

      - name: Create or update nightly release
        uses: taiki-e/create-gh-release-action@v1
        with:
          ref: refs/tags/${{ env.NIGHTLY_TAG }}
          title: Nightly Build
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binaries
        run: |
          cargo build --release -p slipstream-client -p slipstream-server

      - name: Upload binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          ref: refs/tags/${{ env.NIGHTLY_TAG }}
          bin: slipstream-client slipstream-server
          target: x86_64-unknown-linux-gnu
          # Must provide an archive name for multiple binaries
          archive: slipstream-nightly-linux-amd64.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
